fix: fixed description not being long enough in embeds
discordx-ts/templates pull request #80
Opened 2022-11-21 21:01 UTC by Ahmadh26

add a check if description length is not bigger than 0, then use "No description"

a fix for issue #78

2022-11-21 23:09 UTC, VictoriqueMoe requested changes

2022-11-21 23:09 UTC, VictoriqueMoe commented on 2-starter-with-api/src/commands/slashes.ts
> +        .addFields({ name: "Description",  value: cmd.description.length > 0 ? cmd.description : "No description"  });
Add nullish checks

2022-11-21 23:09 UTC, VictoriqueMoe commented on 1-starter/src/commands/slashes.ts
> +        .addFields({ name: "Description", value: cmd.description.length > 0 ? cmd.description : "No description" });
Again, add nullish checks

2022-11-22 02:01 UTC, samarmeena commented on 2-starter-with-api/src/commands/slashes.ts
> +        .addFields({ name: "Description",  value: cmd.description.length > 0 ? cmd.description : "No description"  });
why?

2022-11-22 02:02 UTC, samarmeena commented
fix prettier errors

2022-11-23 09:00 UTC, merged